---
- hosts: 172.31.21.151
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myresult

  - name: i want to display first task result 
    debug:
       msg: "{{myresult}}"