--- 
- hosts: 172.31.21.151
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: Install webserver
    apt:
       name: apache2
       state: present 

  - name: copy file into ansible node side 
    copy: 
       src: staticfile.txt
       dest: /home/ubuntu/mystaticfile.txt
    notify: restart webserver

  - name: copy index.j2 file into ansiblenode
    template: 
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: restart webserver

  - name: Download file and force basic auth
    get_url:
       url: https://get.jenkins.io/war-stable/2.375.1/jenkins.war
       dest: /home/ubuntu/jenkins.war
       force_basic_auth: yes
    notify: restart webserver

  - name: restart webserver
    service: 
       name: apache2
       state: restarted
     