--- 
- hosts: 172.31.21.151
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: Install webserver
    apt:
       name: apache2
       state: present 

  - name: copy file into ansible node side 
    copy: 
       src: staticfile.txt
       dest: /home/ubuntu/mystaticfile.txt