---
- hosts: 172.31.21.151
  become: yes
  tasks:
  - name: Install git 
    apt:
       name: git
       state: present 

  - name: install tree 
    apt:
       name: tree 
       state: present 

  - name: install wget 
    apt: 
       name: wget
       state: present 