---
- hosts: myWebServer
  become: yes
  tasks:
  - name: I want to Install webserver on ubuntu ansible 
    apt:
       name: "{{webpackonUbuntu}}" 
       state: present
    when: ansible_os_family =="Debian"

  - name: I want to start the service 
    service:
       name: "{{webpackonUbuntu}}"
       state: restarted 
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on Redhat 
    yum:
       name: "{{webpackonRedHat}}"
       state: present 
    when: ansible_os_family =="RedHat"

  - name: i want to start webserver on Redhat 
    service:
       name: "{{webpackonRedHat}}"
       state: started
    when: ansible_os_family =="RedHat"
  