---
- name: download tomcat 
  get_url:
     name: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
     dest: /home/ubuntu/apache-tomcat-9.0.56.tar.gz
     force_basic_auth: yes

- name: create tomcat folder
  file: 
     path: /opt/tomcat
     state: directory

- name: extract tomcat tar file 
  command: 
     cmd: sudo tar xzvf apache-tomcat-*tar.gz -C /opt/tomcat --strip-components=1
     creates: opt/tomcat/LICENSE 